In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'retina'
%reload_ext lab_black

In [2]:
import logging
import string
import sys
import os
import pandas as pd
from glob import glob

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from src.figure_utilities import (
    PAGE_HEIGHT,
    ONE_COLUMN,
    TWO_COLUMN,
    save_figure,
    set_figure_defaults,
)

set_figure_defaults()

In [3]:
from src.parameters import PROCESSED_DATA_DIR


def load_error_info():
    data_type, dim = "clusterless", "1D"

    file_paths = glob(
        os.path.join(PROCESSED_DATA_DIR, f"*_{data_type}_{dim}_error_info_80.csv")
    )
    error_info = pd.concat(
        [pd.read_csv(file_path) for file_path in file_paths], axis=0
    ).set_index(["animal", "day", "epoch"])
    error_info = error_info.rename(index={"Cor": "cor"}).rename_axis(
        index={"animal": "Animal ID"}
    )

    return error_info.sort_index()


error_info = load_error_info()
error_info

                     Unnamed: 0  median_error_fold_1  run_median_error_fold_1  \
Animal ID day epoch
bon       3   2       bon_03_02             5.528117                 7.760552
              4       bon_03_04            11.491613                 6.624323
              6       bon_03_06             7.157143                 6.358363
          4   2       bon_04_02             1.631367                 7.406314
              4       bon_04_04             4.914905                 7.013489
...                         ...                  ...                      ...
remy      35  4      remy_35_04             2.711224                 6.938386
          36  2      remy_36_02             7.543883                10.089355
              4      remy_36_04             1.470980                 6.182218
          37  2      remy_37_02             1.470980                 5.875358
              4      remy_37_04             3.092764                 8.374218

                     median_error_fold_2  run_median_error_fold_2  \
Animal ID day epoch
bon       3   2                 6.223104                 7.439726
              4                 3.136468                 5.690885
              6                 6.157244                 6.477880
          4   2                 4.631775                 7.414542
              4                 5.554948                 6.422237
...                                  ...                      ...
remy      35  4                 2.778334                 6.774201
          36  2                 1.485737                 5.074412
              4                 1.463717                 4.861466
          37  2                 1.470980                 4.558478
              4                 1.470980                 4.916855

                     median_error_fold_3  run_median_error_fold_3  \
Animal ID day epoch
bon       3   2                 6.500275                 5.841286
              4                 4.794437                 5.233788
              6                 4.352880                 5.407768
          4   2                 4.205470                 6.260044
              4                 4.724996                 5.320762
...                                  ...                      ...
remy      35  4                 1.470980                 5.225597
          36  2                 1.463717                 4.943726
              4                 1.463717                 4.523808
          37  2                 1.470980                 5.664570
              4                 1.470980                 4.714797

                     median_error_fold_4  run_median_error_fold_4  \
Animal ID day epoch
bon       3   2                 5.400003                 5.997778
              4                 4.854705                 6.154133
              6                 3.685246                 5.029890
          4   2                 2.270659                 5.078133
              4                 2.484229                 4.455811
...                                  ...                      ...
remy      35  4                 1.470980                 4.850134
          36  2                 1.470980                 4.593397
              4                 1.470980                 4.412939
          37  2                 1.470980                 5.278506
              4                 1.470980                 5.370351

                     median_error_fold_5  run_median_error_fold_5
Animal ID day epoch
bon       3   2                 5.506115                 5.890617
              4                 7.310451                 6.453281
              6                 9.775115                 6.627880
          4   2                 1.487949                 6.140797
              4                 2.710827                 6.153673
...                                  ...                      ...
remy      35  4                 1.485737                 5.021919
          36  2                 1.463717                 3.869487
              4                 1.470980                 5.076076
          37  2                 1.470980                 5.117816
              4                 1.485737                 5.441780

[146 rows x 11 columns]

In [4]:
run_median_error = error_info.filter(regex="run_median_error_fold_*", axis=1)
all_median_error = error_info.filter(regex="^median_error_fold_*", axis=1)

In [5]:
run_median_error

                     run_median_error_fold_1  run_median_error_fold_2  \
Animal ID day epoch
bon       3   2                     7.760552                 7.439726
              4                     6.624323                 5.690885
              6                     6.358363                 6.477880
          4   2                     7.406314                 7.414542
              4                     7.013489                 6.422237
...                                      ...                      ...
remy      35  4                     6.938386                 6.774201
          36  2                    10.089355                 5.074412
              4                     6.182218                 4.861466
          37  2                     5.875358                 4.558478
              4                     8.374218                 4.916855

                     run_median_error_fold_3  run_median_error_fold_4  \
Animal ID day epoch
bon       3   2                     5.841286                 5.997778
              4                     5.233788                 6.154133
              6                     5.407768                 5.029890
          4   2                     6.260044                 5.078133
              4                     5.320762                 4.455811
...                                      ...                      ...
remy      35  4                     5.225597                 4.850134
          36  2                     4.943726                 4.593397
              4                     4.523808                 4.412939
          37  2                     5.664570                 5.278506
              4                     4.714797                 5.370351

                     run_median_error_fold_5
Animal ID day epoch
bon       3   2                     5.890617
              4                     6.453281
              6                     6.627880
          4   2                     6.140797
              4                     6.153673
...                                      ...
remy      35  4                     5.021919
          36  2                     3.869487
              4                     5.076076
          37  2                     5.117816
              4                     5.441780

[146 rows x 5 columns]

In [43]:
all_median_error

                     median_error_fold_1  median_error_fold_2  \
Animal ID day epoch
bon       3   2                 5.528117             6.223104
              4                11.491613             3.136468
              6                 7.157143             6.157244
          4   2                 1.631367             4.631775
              4                 4.914905             5.554948
...                                  ...                  ...
remy      35  4                 2.711224             2.778334
          36  2                 7.543883             1.485737
              4                 1.470980             1.463717
          37  2                 1.470980             1.470980
              4                 3.092764             1.470980

                     median_error_fold_3  median_error_fold_4  \
Animal ID day epoch
bon       3   2                 6.500275             5.400003
              4                 4.794437             4.854705
              6                 4.352880             3.685246
          4   2                 4.205470             2.270659
              4                 4.724996             2.484229
...                                  ...                  ...
remy      35  4                 1.470980             1.470980
          36  2                 1.463717             1.470980
              4                 1.463717             1.470980
          37  2                 1.470980             1.470980
              4                 1.470980             1.470980

                     median_error_fold_5
Animal ID day epoch
bon       3   2                 5.506115
              4                 7.310451
              6                 9.775115
          4   2                 1.487949
              4                 2.710827
...                                  ...
remy      35  4                 1.485737
          36  2                 1.463717
              4                 1.470980
          37  2                 1.470980
              4                 1.485737

[146 rows x 5 columns]

In [38]:
run_mean = run_median_error.mean().mean()
run_ci = (
    run_median_error.mean().mean() - 1.96 * run_median_error.mean().std(),
    run_median_error.mean().mean() + 1.96 * run_median_error.mean().std(),
)

print(f"{run_mean:.0f} cm")
print(f"({run_ci[0]:.0f} cm, {run_ci[1]:.0f} cm)")

7 cm
(5 cm, 9 cm)

In [39]:
all_mean = all_median_error.mean().mean()
all_ci = (
    all_median_error.mean().mean() - 1.96 * all_median_error.mean().std(),
    all_median_error.mean().mean() + 1.96 * all_median_error.mean().std(),
)

print(f"{all_mean:.0f} cm")
print(f"({all_ci[0]:.0f} cm, {all_ci[1]:.0f} cm)")

4 cm
(3 cm, 6 cm)

In [47]:
all_median_error.groupby("Animal ID").mean().mean(axis=1)

Animal ID
bon      3.455368
cha     10.273190
con      3.270065
cor     11.822317
dav      4.493994
dud     12.717615
egy      4.822529
fra      1.888672
gov      3.852983
remy     4.595781
dtype: float64

In [48]:
run_median_error.groupby("Animal ID").mean().mean(axis=1)

Animal ID
bon      6.764088
cha     12.639151
con      4.275939
cor      8.149725
dav      6.801500
dud      9.542633
egy      7.788514
fra      6.846580
gov      7.544986
remy     8.097463
dtype: float64

In [49]:
run_median_error.groupby("Animal ID").mean()

,run_median_error_fold_1,run_median_error_fold_2,run_median_error_fold_3,run_median_error_fold_4,run_median_error_fold_5
Animal ID,,,,,
bon,7.653912,6.755657,6.402924,6.349565,6.658382
cha,18.385678,12.906850,10.877161,10.392857,10.633210
con,4.603943,3.909058,3.831395,4.105858,4.929444
cor,12.789762,7.731090,6.788910,6.504183,6.934681
dav,8.306729,6.782899,5.992064,6.301793,6.624015
dud,11.517767,8.377116,10.533053,7.591894,9.693335
egy,9.640610,7.627846,7.049033,7.180198,7.444882
fra,7.559633,6.530244,6.798672,6.661966,6.682386
gov,9.348826,6.831251,6.553278,6.843219,8.148354
remy,19.248531,5.855681,5.263746,5.023152,5.096206

In [156]:
from loren_frank_data_processing import (
    make_tetrode_dataframe,
    make_epochs_dataframe,
    make_neuron_dataframe,
)
from src.parameters import ANIMALS, _BRAIN_AREAS

tetrode_info = make_tetrode_dataframe(ANIMALS)
epoch_info = make_epochs_dataframe(ANIMALS)
neuron_info = make_neuron_dataframe(ANIMALS)
neuron_info = neuron_info.loc[
    (neuron_info.type == "principal")
    & (neuron_info.numspikes > 100)
    & neuron_info.area.isin(_BRAIN_AREAS)
]
n_neurons = (
    neuron_info.groupby(["animal", "day", "epoch"])
    .neuron_id.agg(len)
    .rename("n_neurons")
    .to_frame()
)

epoch_info = epoch_info.join(n_neurons)
is_w_track = epoch_info.environment.isin(["TrackA", "TrackB", "WTrackA", "WTrackB"])
is_remy = (epoch_info.reset_index().set_index(epoch_info.index).animal == "remy") & (
    epoch_info.environment == "wtrack"
)
epoch_keys = epoch_info[(is_w_track & (epoch_info.n_neurons > 9)) | is_remy].index

In [158]:
area = tetrode_info.area.astype(str).str.upper()
area = area.loc[area.isin(_BRAIN_AREAS)]
area = (
    pd.DataFrame(area.reset_index("tetrode_number").loc[epoch_keys])
    .set_index("tetrode_number", append=True)
    .area
)
tetrodes_by_area = area.groupby(["animal", "day", "epoch"]).value_counts()

tetrodes_by_area.groupby(["animal", "area"]).median()

animal  area
Cor     CA1      8.0
        CA3      3.0
bon     CA1     11.0
        CA3     13.0
cha     CA1      6.5
        CA2      3.0
        CA3      3.0
con     CA1      4.0
        CA3      6.0
dav     CA1      7.0
        CA3      3.0
dud     CA1      4.0
        CA3      8.0
egy     CA1      4.0
        CA2      3.0
        CA3      3.0
fra     CA1      5.0
        CA2      3.0
        CA3      8.0
gov     CA1      6.0
        CA2      5.0
        CA3      2.0
remy    CA1     24.0
Name: area, dtype: float64